package com.webreach.mirth.plugins.xdsquerywizard;

import org.netbeans.spi.wizard.WizardPage;

public class DateRangePage extends WizardPage
{
    
    /** Creates new form DestinationConnectorPage */
    public DateRangePage()
    {
        initComponents();
        startDate.getEditor().setName("startDate");
        endDate.getEditor().setName("endDate");
        startDate.getEditor().setEditable(false);
        endDate.getEditor().setEditable(false);
    }
    public static final String getDescription() {
        return "Choose lookup date range";
    }
    
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        portLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        portLabel1 = new javax.swing.JLabel();
        startDate = new com.webreach.mirth.client.ui.components.MirthDatePicker();
        endDate = new com.webreach.mirth.client.ui.components.MirthDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));
        portLabel.setText("Start Date:");

        jLabel1.setText("Select date range for document lookup");

        portLabel1.setText("End Date:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(portLabel1)
                            .add(portLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(endDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(startDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(portLabel)
                    .add(startDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(endDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(portLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.webreach.mirth.client.ui.components.MirthDatePicker endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel portLabel;
    private javax.swing.JLabel portLabel1;
    private com.webreach.mirth.client.ui.components.MirthDatePicker startDate;
    // End of variables declaration//GEN-END:variables
    
}
