package com.webreach.mirth.plugins.ihepixwizard;

import java.awt.Component;
import java.util.List;

import org.netbeans.spi.wizard.WizardPage;

import com.webreach.mirth.client.core.ClientException;
import com.webreach.mirth.client.ui.PlatformUI;

public class DestinationConnectorPage extends WizardPage
{
    
    /** Creates new form DestinationConnectorPage */
    public DestinationConnectorPage()
    {
        initComponents();
        
        try
        {
            List<String> actorList = (List<String>) PlatformUI.MIRTH_FRAME.mirthClient.invokePluginMethod("IHE Configuration", "getActorNames", null);
            if(actorList == null || actorList.size() == 0)
            {
                IHEActorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"No actors found"}));
            }
            else
            {
                IHEActorComboBox.setModel(new javax.swing.DefaultComboBoxModel(actorList.toArray()));
            }
        }
        catch (ClientException e)
        {
            PlatformUI.MIRTH_FRAME.alertException(e.getStackTrace(), e.getMessage());
            IHEActorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"No actors found"}));
        }
        
        IHEActorComboBox.setName("IHEActor");
    }
    
    public static final String getDescription() {
        return "Choose destination settings";
    }
    
    protected String validateContents (Component component, Object o) {
        
        if (((String)IHEActorComboBox.getSelectedItem()).equalsIgnoreCase("No actors found")) {
            return "You must specify an actor.";
        } else {
            return null;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IHEActorComboBox = new javax.swing.JComboBox();
        IHEActorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("This channel will connect to IHE PIX.");

        jLabel2.setText("You must first specify the path of the xml config in the IHE Configuration Plugin.");

        IHEActorLabel.setText("IHE Actor:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(IHEActorLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(IHEActorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IHEActorLabel)
                    .add(IHEActorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox IHEActorComboBox;
    private javax.swing.JLabel IHEActorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
