package com.webreach.mirth.plugins.xdsquerywizard;

import org.netbeans.spi.wizard.WizardPage;

public class PatientIDMappingPage extends WizardPage
{
    
    private static final String PID19 = "msg['PID']['PID.19']['PID.19.1'].toString()";
	private static final String PID18 = "msg['PID']['PID.18']['PID.18.1'].toString()";
	private static final String PID4 = "msg['PID']['PID.4']['PID.4.1'].toString()";
	private static final String PID3 = "msg['PID']['PID.3']['PID.3.1'].toString()";
	private static final String PID2 = "msg['PID']['PID.2']['PID.2.1'].toString()";
	/** Creates new form SourceConnectorPage */
    public PatientIDMappingPage()
    {
        initComponents();
        customTextField.setName("mapping");
        customTextField.setText(PID2);
        
    }
    
    public static final String getDescription() {
        return "Choose patient id mapping";
    }
    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        customTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pid21RadioButton = new javax.swing.JRadioButton();
        pid31RadioButton = new javax.swing.JRadioButton();
        pid41RadioButton = new javax.swing.JRadioButton();
        pid181RadioButton = new javax.swing.JRadioButton();
        pid191RadioButton = new javax.swing.JRadioButton();
        customRadioButton = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        customTextField.setEditable(false);
        customTextField.setEnabled(false);

        jLabel1.setText("Select which patient id field you would like to use:");

        pid21RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pid21RadioButton);
        pid21RadioButton.setSelected(true);
        pid21RadioButton.setText("PID.2.1 (Internal Patient ID)");
        pid21RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pid21RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pid21RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customSelected(evt);
            }
        });

        pid31RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pid31RadioButton);
        pid31RadioButton.setText("PID.3.1 (External Patient Identifier List)");
        pid31RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pid31RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pid31RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customSelected(evt);
            }
        });

        pid41RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pid41RadioButton);
        pid41RadioButton.setText("PID.4.1 (Alternate Patient ID)");
        pid41RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pid41RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pid41RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customSelected(evt);
            }
        });

        pid181RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pid181RadioButton);
        pid181RadioButton.setText("PID.18.1 (Patient Account Number)");
        pid181RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pid181RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pid181RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customSelected(evt);
            }
        });

        pid191RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pid191RadioButton);
        pid191RadioButton.setText("PID.19.1 (Patient SSN Number)");
        pid191RadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pid191RadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pid191RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customSelected(evt);
            }
        });

        customRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(customRadioButton);
        customRadioButton.setText("Custom:");
        customRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        customRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        customRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customSelected(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(pid21RadioButton)
                    .add(pid31RadioButton)
                    .add(pid41RadioButton)
                    .add(pid181RadioButton)
                    .add(pid191RadioButton)
                    .add(layout.createSequentialGroup()
                        .add(customRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(customTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .add(28, 28, 28)
                .add(pid21RadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pid31RadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pid41RadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pid181RadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pid191RadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(customRadioButton)
                    .add(customTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customSelected(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customSelected
// TODO add your handling code here:
        if (customRadioButton.isSelected()){
            customTextField.setEnabled(true);
            customTextField.setEditable(true);
            customTextField.requestFocus();
        }else{
            customTextField.setEnabled(false);
            customTextField.setEditable(false);
        }
        if(pid21RadioButton.isSelected()){
            customTextField.setText(PID2);
        }else if (pid31RadioButton.isSelected()){
            customTextField.setText(PID3);
        }else if (pid41RadioButton.isSelected()){
            customTextField.setText(PID4);
        }else if (pid181RadioButton.isSelected()){
            customTextField.setText(PID18);
        }else if (pid191RadioButton.isSelected()){
            customTextField.setText(PID19);
        }
    }//GEN-LAST:event_customSelected
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton customRadioButton;
    private javax.swing.JTextField customTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton pid181RadioButton;
    private javax.swing.JRadioButton pid191RadioButton;
    private javax.swing.JRadioButton pid21RadioButton;
    private javax.swing.JRadioButton pid31RadioButton;
    private javax.swing.JRadioButton pid41RadioButton;
    // End of variables declaration//GEN-END:variables
    
}
